### ISSUE TITLE
Add option to save last used settings in the GUI

### ISSUE THREAD

**Issue by efa** [alus-it/AirspaceConverter#54]
can be usefull an option to save the last used settings/user preferences in the GUI. For example the latitude/longitude settings, and output file format settings

**Comment by alus-** [comment]
I don't find this feature so relevant at the moment.
It can be a lot of work to find the proper place where to save the settings on the various platforms for a very little advantage.
I prefer the users going trough all the options on the UI every time being aware of what they are doing instead of relying on the previous already saved settings.
