### ISSUE TITLE
Check airspaces name are encoded right (UTF-8/ANSI)

### ISSUE THREAD

**Issue by efa** [alus-it/AirspaceConverter#62]
just to remember to check

**Comment by alus-** [comment]
It should be everywhere Unicode (UTF-8) but OpenAir files are usually encoded in ANSI (ISO8859-1).
So the problem occurs when reading and writing names on OpenAir files.
Anyway not all OpenAir files are encoded in ANSI, some are encoded in UTF-8 with BOM:
https://www.postfrontal.com/forum/topic.asp?TOPIC_ID=7897

Therefore the solution here implemented is the following:
We expect everywhere UTF-8 except in OpenAir files where we expect ANSI by default. Anyway when reading an OpenAir file, if it starts with a UTF-8 BOM in that specific case the file will be treated as UTF-8. This means that OpenAir input files if encoded in UTF-8 must have the UTF-8 BOM (0xEF 0xBB 0xBF) at the beginning in order to be read correctly.
The output in OpenAir will be **always** encoded in ANSI.
